---
title: Normandie Ai Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: ''
baseurl: ''
plugins:
- jekyll-postcss
postcss:
  cache: false
